### ISSUE TITLE
How do I use this augment data?

### ISSUE THREAD

**Issue by JiangWeiHn** [conradry/copy-paste-aug#2]
I have successfully run your program. Now I want to know how to use the data， to train the model directly, or to save the data and train the model with the original data?

**Comment by conradry** [comment]
This repo just implements the augmentation. Hopefully these resources are useful to you:

Albumentations for pytorch: https://albumentations.ai/docs/examples/pytorch_semantic_segmentation/
Albumentations for Tensorflow: https://albumentations.ai/docs/examples/tensorflow-example/

**Comment by JiangWeiHn** [comment]
thanks a lot

**Comment by haythemtellili** [comment]
Hello, Did you manage to use this augmented data ?
