### ISSUE TITLE
Reproduce results in Paper

### ISSUE THREAD

**Issue by vdopp234** [conradry/copy-paste-aug#3]
Have you been able to reproduce the results achieved in the paper with this unofficial implementation?

**Comment by conradry** [comment]
That isn't the goal of this repository. The copy-paste augmentation is the only novel method introduced in the paper. The model architecture is just a standard Mask-RCNN using one of a few possible backbones (EfficientNet, ResNet, etc.), there are implementations of those elsewhere.

To actually use copy-paste in model training it may be easiest to adapt the augmentation code presented here for use with detectron2: https://detectron2.readthedocs.io/en/latest/tutorials/augmentation.html. I'll consider adding an example notebook for this when I have some time.

**Comment by vdopp234** [comment]
Got it, thank you

**Comment by rederyang** [comment]
Currently I'm also considering to integrate copy-paste data augmentation into Detectron2. But I found that Detectron2 might not support multi-sample data augmentation so well, like mixup, cutmix and copy-paste. This confused me a lot.
So, I am wondering what the best practice to integrate such augmentations into Detectron2 is. Hoping for your idea about this.
