### ISSUE TITLE
How can I use the copy-paste augmentation without albumentation framework?

### ISSUE THREAD

**Issue by Huuush** [conradry/copy-paste-aug#7]
As a user design data augmentation pipline that could be used in torchvision.transform.Compose or [Extend and use custom pipelines](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/data_pipeline.md), for excample. Thanks!

**Comment by conradry** [comment]
The code to implement copy-paste is very simple, see copy_paste.py. Take the functions that blend images and paste bboxes and masks and create functions that work with those APIs. I'm only interested in supporting albumentations.
