### ISSUE TITLE
How To Visualize Augmented Images in As presented in Fig 2.

### ISSUE THREAD

**Issue by Eldad27** [conradry/copy-paste-aug#8]
@conradry Very interesting work done. Thanks. The 'example.ipynb' does not display augmented images as presented in figure 2 of the original paper. Can you advise on how to reproduce and visualize the augmentation effect as observed in the newly created images as presented in Fig 2 of the paper?

**Comment by craston** [comment]
@Eldad27 If you have solved this, could you please post a snippet for the code?
